# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Home(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(600, 400)
        HomeWindow.setMaximumSize(QtCore.QSize(600, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/ubuntu/modules-OctoCAD/gui/v-20200817/logo_transparent_enlarged.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HomeWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_design = QtWidgets.QPushButton(self.groupBox)
        self.btn_design.setMinimumSize(QtCore.QSize(0, 200))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/ubuntu/modules-OctoCAD/gui/v-20200817/design.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_design.setIcon(icon1)
        self.btn_design.setIconSize(QtCore.QSize(80, 80))
        self.btn_design.setObjectName("btn_design")
        self.gridLayout.addWidget(self.btn_design, 0, 0, 1, 1)
        self.btn_model = QtWidgets.QPushButton(self.groupBox)
        self.btn_model.setMinimumSize(QtCore.QSize(0, 200))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/ubuntu/modules-OctoCAD/gui/v-20200817/3d-modeling.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_model.setIcon(icon2)
        self.btn_model.setIconSize(QtCore.QSize(80, 80))
        self.btn_model.setObjectName("btn_model")
        self.gridLayout.addWidget(self.btn_model, 0, 1, 1, 1)
        self.btn_info = QtWidgets.QPushButton(self.groupBox)
        self.btn_info.setMinimumSize(QtCore.QSize(0, 200))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/ubuntu/modules-OctoCAD/gui/v-20200817/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_info.setIcon(icon3)
        self.btn_info.setIconSize(QtCore.QSize(80, 80))
        self.btn_info.setObjectName("btn_info")
        self.gridLayout.addWidget(self.btn_info, 1, 0, 1, 1)
        self.btn_about = QtWidgets.QPushButton(self.groupBox)
        self.btn_about.setMinimumSize(QtCore.QSize(0, 200))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/ubuntu/modules-OctoCAD/gui/v-20200817/about-us.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_about.setIcon(icon4)
        self.btn_about.setIconSize(QtCore.QSize(80, 80))
        self.btn_about.setObjectName("btn_about")
        self.gridLayout.addWidget(self.btn_about, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "OctoCAD©"))
        self.groupBox.setTitle(_translate("HomeWindow", "Select"))
        self.btn_design.setText(_translate("HomeWindow", "Design"))
        self.btn_model.setText(_translate("HomeWindow", "Generate 3-D model"))
        self.btn_info.setText(_translate("HomeWindow", "Help"))
        self.btn_about.setText(_translate("HomeWindow", "About Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QMainWindow()
    ui = Home()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
